In [4]:
#Numpy
import numpy as np
data=np.array([
 #10 students 5 subjects
#Math,Physics,Chemistry,Biology,English
    [85, 90, 78, 88, 92],
    [76, 81, 85, 79, 88],
    [90, 95, 89, 93, 91],
    [68, 72, 70, 75, 71],
    [88, 86, 90, 85, 89],
    [92, 88, 91, 90, 93],
    [74, 78, 76, 80, 79],
    [81, 85, 83, 87, 84],
    [95, 92, 96, 94, 97],
    [70, 73, 71, 74, 72]
])
print(data)

[[85 90 78 88 92]
 [76 81 85 79 88]
 [90 95 89 93 91]
 [68 72 70 75 71]
 [88 86 90 85 89]
 [92 88 91 90 93]
 [74 78 76 80 79]
 [81 85 83 87 84]
 [95 92 96 94 97]
 [70 73 71 74 72]]


In [26]:
print("***Creation Methods in Numpy***")
print("zeros")
print(np.zeros((3,3)))
print("Ones")
print(np.ones((2,4)))
print("empty")
print(np.empty((2,4)))
print("arange")
print(np.arange(0,20,2))
print("linspace")
print(np.linspace(0,100,11)) #11 evenly spaced numbers from 0-100
print("eye")
print(np.eye(4))
print("uniform random")
print(np.random.rand(3,3))
print("random integer")
print(np.random.randint(50,100,(5,3)))
      

***Creation Methods in Numpy***
zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
empty
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arange
[ 0  2  4  6  8 10 12 14 16 18]
linspace
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
eye
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
uniform random
[[0.78331955 0.17703746 0.2950145 ]
 [0.05265822 0.04339945 0.25164308]
 [0.60104223 0.24975103 0.99121423]]
random integer
[[60 78 81]
 [60 93 96]
 [80 54 97]
 [74 65 66]
 [83 68 75]]


In [31]:
print("***Array Properties***")
print("shape")
print(data.shape)
print("dimension")
print(data.ndim)
print("data type and item size")
print(data.dtype)
print(data.itemsize)

***Array Properties***
shape
(10, 5)
dimension
2
data type and item size
int64
8


In [24]:
print("***Indexing & Slicing***")
print("1st student marks in maths",data[0,0])
print("1st student all marks",data[0])
print("all math scores",data[:,0])
print("all first three students, first 2 subjects")
print(data[0:3, 0:2])
print("student who scored more than 85 in maths",data[data[:,0]>85])
print("student who scored more than 85 in maths and physics"),data[(data[:,0]>85) & (data[:,1]>85)]

***Indexing & Slicing***
1st student marks in maths 85
1st student all marks [85 90 78 88 92]
all math scores [85 76 90 68 88 92 74 81 95 70]
all first three students, first 2 subjects
[[85 90]
 [76 81]
 [90 95]]
student who scored more than 85 in maths [[90 95 89 93 91]
 [88 86 90 85 89]
 [92 88 91 90 93]
 [95 92 96 94 97]]
student who scored more than 85 in maths and physics


(None,
 array([[90, 95, 89, 93, 91],
        [88, 86, 90, 85, 89],
        [92, 88, 91, 90, 93],
        [95, 92, 96, 94, 97]]))

In [36]:
print("***Reshaping***")
print("Reshaped to 5*10")
print(data.reshape(5,10))
print("Flattened to 1D")
print(data.flatten())
flat=data.flatten()
print("Flatten to 1D upto 20 elements")
print(flat[:20])
print("Add dimension")
expanded=np.expand_dims(data,axis=0)
print(expanded.shape)
print("Transpose")
print(data.T)

***Reshaping***
Reshaped to 5*10
[[85 90 78 88 92 76 81 85 79 88]
 [90 95 89 93 91 68 72 70 75 71]
 [88 86 90 85 89 92 88 91 90 93]
 [74 78 76 80 79 81 85 83 87 84]
 [95 92 96 94 97 70 73 71 74 72]]
Flattened to 1D
[85 90 78 88 92 76 81 85 79 88 90 95 89 93 91 68 72 70 75 71 88 86 90 85
 89 92 88 91 90 93 74 78 76 80 79 81 85 83 87 84 95 92 96 94 97 70 73 71
 74 72]
Flatten to 1D upto 20 elements
[85 90 78 88 92 76 81 85 79 88 90 95 89 93 91 68 72 70 75 71]
Add dimension
(1, 10, 5)
Transpose
[[85 76 90 68 88 92 74 81 95 70]
 [90 81 95 72 86 88 78 85 92 73]
 [78 85 89 70 90 91 76 83 96 71]
 [88 79 93 75 85 90 80 87 94 74]
 [92 88 91 71 89 93 79 84 97 72]]
