In [4]:
#Numpy
import numpy as np
data=np.array([
 #10 students 5 subjects
#Math,Physics,Chemistry,Biology,English
    [85, 90, 78, 88, 92],
    [76, 81, 85, 79, 88],
    [90, 95, 89, 93, 91],
    [68, 72, 70, 75, 71],
    [88, 86, 90, 85, 89],
    [92, 88, 91, 90, 93],
    [74, 78, 76, 80, 79],
    [81, 85, 83, 87, 84],
    [95, 92, 96, 94, 97],
    [70, 73, 71, 74, 72]
])
print(data)

[[85 90 78 88 92]
 [76 81 85 79 88]
 [90 95 89 93 91]
 [68 72 70 75 71]
 [88 86 90 85 89]
 [92 88 91 90 93]
 [74 78 76 80 79]
 [81 85 83 87 84]
 [95 92 96 94 97]
 [70 73 71 74 72]]


In [26]:
print("***Creation Methods in Numpy***")
print("zeros")
print(np.zeros((3,3)))
print("Ones")
print(np.ones((2,4)))
print("empty")
print(np.empty((2,4)))
print("arange")
print(np.arange(0,20,2))
print("linspace")
print(np.linspace(0,100,11)) #11 evenly spaced numbers from 0-100
print("eye")
print(np.eye(4))
print("uniform random")
print(np.random.rand(3,3))
print("random integer")
print(np.random.randint(50,100,(5,3)))
      

***Creation Methods in Numpy***
zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
empty
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arange
[ 0  2  4  6  8 10 12 14 16 18]
linspace
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
eye
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
uniform random
[[0.78331955 0.17703746 0.2950145 ]
 [0.05265822 0.04339945 0.25164308]
 [0.60104223 0.24975103 0.99121423]]
random integer
[[60 78 81]
 [60 93 96]
 [80 54 97]
 [74 65 66]
 [83 68 75]]


In [31]:
print("***Array Properties***")
print("shape")
print(data.shape)
print("dimension")
print(data.ndim)
print("data type and item size")
print(data.dtype)
print(data.itemsize)

***Array Properties***
shape
(10, 5)
dimension
2
data type and item size
int64
8


In [ ]:
/